### ISSUE TITLE
Список скрытых рассказов

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#1]
_From @EpicMan2 on February 14, 2016 13:7_

Используя поиск, есть возможность увидеть список скрытых модерацией рассказов, либо ещё не допущенных к публикации. Список действий:
1. Задать в поиске сортировку по дате
2. Нажать поиск

_Copied from original issue: RuFimFiction/StoriesEP#1_

**Comment by tanriol** [comment]
Уже исправлено в ветке development (где-то около 184e427).

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#18
