### ISSUE TITLE
Добавить пользователям возможность скрывать комментарии выбранного пользователя

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#10]
_From @WillWisp on February 15, 2016 11:43_

Под фиком комментарий должен отображаться, как скрытый, но с возможностью развернуть. #5 

_Copied from original issue: RuFimFiction/StoriesEP#10_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#29
