### ISSUE TITLE
Перелистывание страниц на главной

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#12]
_From @WillWisp on February 15, 2016 11:51_

Добавить возможность перелистывать с главной страницы https://stories.everypony.ru/
Такая страница уже существует https://stories.everypony.ru/stream/stories/

_Copied from original issue: RuFimFiction/StoriesEP#12_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#31
