### ISSUE TITLE
Комментарии лесенкой

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#14]
Древовидные ("лесенкой") комментарии.
[Пример](http://tabun.everypony.ru/blog/stories/148865.html)

- [ ] Комментарий может иметь "родительский" комментарий, на который он отвечает
- [ ] Возможность ответа на конкретный комментарий
- [ ] Возможность скрывать ветвь комментариев (#15)

(входит в #5)

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#32
