### ISSUE TITLE
Автоскрытие комментариев с сильно отрицательным рейтингом

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#17]
_From @WillWisp on February 15, 2016 12:5_

#5 
#16 
Комментарии с рейтингом -5 и ниже скрываются автоматически. Возможность раскрыть комментарии.

_Copied from original issue: RuFimFiction/StoriesEP#17_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#35
