### ISSUE TITLE
Чтение скрытых рассказов

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#2]
_From @EpicMan2 on February 14, 2016 13:8_

Рассказы, скрытые модераторами можно легко прочитать путём использования функции преобразования рассказа в формат fb2. Для этого надо воспользоваться #1, выбрать нужный рассказ, и нажать на кнопку преобразования в fb2. Далее текст преобразуется в файл, и его можно будет прочитать.

_Copied from original issue: RuFimFiction/StoriesEP#2_

**Comment by tanriol** [comment]
@WillWisp, считаем ли мы проблемой то, что рассказ можно скачать по прямой ссылке? Её нигде не видно, но человек, знающий id и название рассказа, в принципе может сделать её вручную и скачать последний файл этого рассказа, который скачивали до него.

**Comment by andreymal** [comment]
Добавить к ссылке какой-нибудь md5 от какого-нибудь секретного ключика, который хранить в БД — дело десяти минут.

**Comment by andreymal** [comment]
Название рассказа, кстати, знать необязательно, достаточно id. За сутки неспешной (чтоб fail2ban не забанил) работы скрипта на питоне можно слить почти всю базу со всеми рассказами и даже комментариями к ним.

![](https://i.imgur.com/IPamDAl.jpg)

**Comment by tanriol** [comment]
@andreymal, без названия ты можешь запросить story_download, но туда проверку прав доступа вроде легко вставить. А с названием можно напрямую запросить уже сгенерированный файл, который отдаёт напрямую nginx..

**Comment by andreymal** [comment]
Добавить рандомную строку в ссылку и убрать story_download совсем.

**Comment by tanriol** [comment]
> ...md5 от какого-нибудь секретного ключика, который хранить в БД...

Можно ещё так - добавить туда часть sha256 от текста рассказа. Если он у тебя есть, то зачем тебе скачивать? :-)

**Comment by andreymal** [comment]
Ссылка будет меняться при каждом редактировании, что в некоторых ситуациях не есть хорошо; рандомной строки хватит (даже md5 по вкусу)

**Comment by andreymal** [comment]
(хотя немного погорячился «убрать story_download совсем», архивы ведь кто-то создавать должен, а создавать заранее — пустая трата места)

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#21
