### ISSUE TITLE
Возможность авторов писать комменты к своим рассказам в черновиках и в “Новые”

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#20]
_From @WillWisp on February 15, 2016 12:20_

#5 
Возможность авторов писать комменты к своим рассказам в черновиках и в “Новые”. Sic! Новые, которые отображаются у модератора (премодерация)

_Copied from original issue: RuFimFiction/StoriesEP#20_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#37
