### ISSUE TITLE
Возможность вывода лучшего отзыва

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#26]
_From @WillWisp on February 15, 2016 12:55_

#21 
Возможность отображения отзыва ( во всплывающем окне) с самым высоким рейтингом, при нажатии на соответствующую кнопку в описании фика.

_Copied from original issue: RuFimFiction/StoriesEP#26_

**Comment by tanriol** [comment]
Возможно, в варианте "показывать (достаточно хорошие) отзывы в порядке по рейтингу"?

**Comment by WillWisp** [comment]
Если под катом, то это имеет смысл. А тут имеется ввиду, чтобы посмотреть отзыв, не надо было заходить под кат, а смотреть прямо с главной.

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#44
