### ISSUE TITLE
Организация ленты комментов под фиком

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#28]
_From @WillWisp on February 15, 2016 13:2_

#27 
#5 
Возможность по нажатию кнопки включать комментарии к отдельным главам в общие комментарии.
Под комментарием отображается, к какой он главе.
Возможность скрывать комменты к определённым главам.

_Copied from original issue: RuFimFiction/StoriesEP#28_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#46
