### ISSUE TITLE
Редактирование комментов

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#30]
_From @WillWisp on February 15, 2016 13:7_

#5 
Возможность редактировать свои комменты в течении 3 минут после публикации.
В случае, если на коммент отвечают до истечении 3 минут, то возможность редактировать блокируется

_Copied from original issue: RuFimFiction/StoriesEP#30_

**Comment by tanriol** [comment]
@WillWisp, а оригинальный текст комментария хранить требуется или он не нужен?

**Comment by EpicMan2** [comment]
@tanriol, лично я предлагаю оставлять его видимым только для модераторов.

**Comment by andreymal** [comment]
Лично я предлагаю оставлять его видимым вообще всем, а также открыть имеющиеся ныне логи модерации и всё такое остальное. Ибо нефиг модерастить.

**Comment by Orhideous** [comment]
Насколько востребованным будет хранение всех ревизий комментариев?

**Comment by WillWisp** [comment]
Большая часть отредаченых комментов будут касаться исправления ошибок в них. Не думаю, что стоит хранить подобное. Если будут случаи, которые потребуют подобное, тогда и будем думать.

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#48
