### ISSUE TITLE
Статистика рассказа

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#4]
_From @EpicMan2 on February 14, 2016 13:18_

Добавить возможность просмотра статистики рассказа, в которой будет:
Количество слов в рассказе (букв)
Голосование за рассказ по времени
Количество просмотров рассказа по времени

Возможно, добавить что-то ещё в этот список.

_Copied from original issue: RuFimFiction/StoriesEP#4_

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#23
