### ISSUE TITLE
Откат связанных с рейтингом изменений к состоянию продакшена

### ISSUE THREAD

**Issue by Orhideous** [RuFimFiction/ponyFiction#41]
### Причина
Для того, чтобы менять что-то, надо знать, какие изменения делать. Это возможно лишь с точки зрения data-driven decision, и без аналитики и аргументации исследованием лезть в систему рейтинга, какой бы она плохой не была, не стоит.
Это *не* значит, что рейтинг меняться не будет: @RuFimFiction/contributors решили, что проще будет начать с нынешнего варианта, того, который работает на продакшене.

**Comment by andreymal** [comment]
Форкал бы тогда изначально репозиторий Веона, а не свой.

**Comment by Orhideous** [comment]
Такой вариант занял бы больше времени.

**Comment by Orhideous** [comment]
Дальнейшая работа (анализ статистики и разработка модели) будет в #42
