### ISSUE TITLE
Разработать адекватную модель рейтинга

### ISSUE THREAD

**Issue by Orhideous** [RuFimFiction/ponyFiction#42]

**Comment by andreymal** [comment]
Странно, что у кого-то есть сомнения, какая же модель рейтинга является адекватной.

**Comment by Orhideous** [comment]
Вот у меня есть.
Я не видел распределения оценок. Не смотрел на временные аномалии. Не работал с этими данными.

**Comment by andreymal** [comment]
Смотреть распределение и аномалии на текущем подковковом рейтинге, который не понимает вообще никто? Мсье знает толк.

**Comment by Orhideous** [comment]
@andreymal, твой сарказм неуместен.
В базе данных хранится полная история рейтинга, плюсы и минусы. Это все данные, что у нас есть. Они необработанные, но для статистического анализа это и не нужно.
И смотреть надо как раз на них.

**Comment by andreymal** [comment]
Было бы очень интересно узнать статистику по попутавшим плюс и минус.

**Comment by Orhideous** [comment]
Косвенным путем можно выяснить и это. Более того, у нас хранятся и просмотры.

**Comment by tanriol** [comment]
Не исключено, что предложенный @andreymal рейтинг действительно окажется существенно лучше. Но на первом этапе не хочется связываться с изменениями рейтинга вообще, чтобы не оказаться погребёнными под волной "вы всё испортили и рейтинг теперь не рейтинг".

**Comment by Orhideous** [comment]
Согласен с @tanriol'ом.

**Comment by andreymal** [comment]
Так вы уже погребены ж. С самого появления подковок. =)

**Comment by Orhideous** [comment]
@andreymal Ты обходишь вниманием более важное. Данные в БД не изменялись и не пересчитывались необратимо.

**Comment by andreymal** [comment]
Зато пользователи голосовали необратимо по другому из-за убогого интерфейса. И тебе теперь сидеть считать, можно ли вообще считать эти данные корректными.)

**Comment by Orhideous** [comment]
А кто этим будет заниматься, решит @WillWisp.
