### ISSUE TITLE
Цвета жанров не отображаются

### ISSUE THREAD

**Issue by WillWisp** [RuFimFiction/ponyFiction#44]
Цвета жанров не отображаются

**Comment by tanriol** [comment]
Цвета теперь задаются в базе данных (например, через админку) для большинства страниц, нужно их внести туда.

**Comment by tanriol** [comment]
Поправка: тут  всё веселее, на части страниц цвета задаются в админке, а на части в виде CSS.

**Comment by andreymal** [comment]
Ага, недовыпилил CSS в связи с сложностью работы с виджетами.

**Comment by tanriol** [comment]
@andreymal, вероятно, ты в курсе - там вообще есть какой-то штатный способ прокинуть цвет в виджет? Или на этой проблеме прошлая попытка и завершилась?

**Comment by andreymal** [comment]
Хз, я себе просто всё перенёс на wtforms и там в виджете из базы забираю

**Comment by tanriol** [comment]
Предварительно поправлено в d0214eb, нужно допилить виджеты (а лучше вернуться на стандартные), но это меньший приоритет.

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#54
