### ISSUE TITLE
При поиске по жанрам не отображаются рассказы

### ISSUE THREAD

**Issue by WillWisp** [RuFimFiction/ponyFiction#45]
При поиске по жанрам не отображаются рассказы.
Единственный рассказ, который отображается - http://stories.alterpony.ru/story/11649/

**Comment by andreymal** [comment]
Это не баг, а какой-то нехороший админ забыл выполнить `python manage.py initsphinx`.

**Comment by tanriol** [comment]
Команда `vagga manage.py initsphinx` добавлена в документацию.
