### ISSUE TITLE
Изменение шрифта не работает в фиках с несколькими главами

### ISSUE THREAD

**Issue by WillWisp** [RuFimFiction/ponyFiction#47]
Изменения шрифта вроде размера или засечки/не засечки работают только у фиков с одной главой, то есть, где весь текст на заглавной странице, в фиках где есть несколько глав оно не работает, не важно выбрана глава или текст целиком.

**Comment by andreymal** [comment]
Я ещё летом починил.

**Comment by WillWisp** [comment]
Тем не менее, сейчас этого на http://stories.alterpony.ru/ нет. Если есть желание, то можешь заняться.
