### ISSUE TITLE
Система рейтинга

### ISSUE THREAD

**Issue by WillWisp** [RuFimFiction/ponyFiction#48]
- [ ] Оценка фиков +1 -1
- [ ] Оценку можно менять раз в неделю
- [ ] При 2/3 положительных оценок к рассказу, он выходит на страницу "интересные"
- [ ] При 2/3 отрицательных оценок к рассказу, он выходит на страницу "дикий фанфикшн"
- [ ] Соотношение оценок влияет на выход на ту или иную страницу при количестве оценок от пользователей не менее 10
- [ ] Фики, которые не попали в категории "интересные" или "дикие" остаются в "новое"

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#57
