### ISSUE TITLE
AJAX на страницах

### ISSUE THREAD

**Issue by EpicMan2** [RuFimFiction/ponyFiction#63]
Перевести наш любимый сториз на AJAX. Примером может послужить:
[https://stories.andreymal.org/](https://stories.andreymal.org)

**Comment by tanriol** [comment]
Уточни пожалуйста, какие функции ты хочешь перевести на AJAX? Или всё-всё-всё?

**Comment by EpicMan2** [comment]
Переходы по рассказам, профилям, поиску (желательно), дополнительным страницам (справка и т.д.).

**Comment by tanriol** [comment]
То есть полномасштабный переход на одностраничное приложение, сколько я понимаю. Если я не ошибаюсь, это необходимость перерабатывать все шаблоны с шаблонизатора Django на (что-то из JS-шаблонизаторов). Крупномасштабная и долгосрочная затея.

**Comment by tanriol** [comment]
А что именно мы на этом выиграем? Перестанем терять производительность на шаблонах Django?

**Comment by EpicMan2** [comment]
Как минимум - получим удобство для пользователей. Им не надо ждать загрузки новой страницы, а достаточно подождать пока подгрузит AJAX. А скопировать реализацию с Андреймаловского сорца получится, или он слишком отличается от нашего?

**Comment by tanriol** [comment]
> Им не надо ждать загрузки новой страницы, а достаточно подождать пока подгрузит AJAX.

Собственно, именно об этом у меня и вопрос - даёт ли AJAX существенный выигрыш, если приходится перегружать почти всю страницу? Понятно, что через него должны работать рейтинг, избранное, комментарии - те места, где изменяются только детали.

> А скопировать реализацию с Андреймаловского сорца получится, или он слишком отличается от нашего?

С учётом того, куда он ушёл - лопнем, по-моему.

**Comment by andreymal** [comment]
>Крупномасштабная и долгосрочная затея.

Хз, я как-то за три вечера управился

**Comment by idem-id** [comment]
> Собственно, именно об этом у меня и вопрос - даёт ли AJAX существенный выигрыш, если приходится перегружать почти всю страницу?

Нет, не даёт

**Comment by andreymal** [comment]
На моём Intel Core i5-4210U почему-то даёт.

**Comment by idem-id** [comment]
> Понятно, что через него должны работать рейтинг, избранное, комментарии - те места, где изменяются только детали.

Если только это, то да. А если 80-90% странички, то игра не стоит свеч.

**Comment by andreymal** [comment]
Вы все забываете про обработку CSS, выполнение кучи js (jQuery, Bootstrap, вот это вот всё), загрузку картинок из кэша и всякую прочую дребедень помимо собственно трафика. На моей системе главная stories.andreymal.org без AJAX загружается за 649 мс (согласно профилировщику Chrome), а с AJAX — за 78 мс.

**Comment by Orhideous** [comment]
Гм. В текущей реализации он и так есть.
Или вы говорите сейчас о новых шаблонах?

**Comment by andreymal** [comment]
Они про SPA-подобное

**Comment by Orhideous** [comment]
Нннну. делать SPA можно будет после того, как устаканится внутренний API. Хотя, надо посмотреть новые шаблоны и подумать.

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#65
