### ISSUE TITLE
Добавить инструкции по настройке HTTPS

### ISSUE THREAD

**Issue by tanriol** [RuFimFiction/ponyFiction#64]
Дружбомагия - дружбомагией, а хотя бы пароли надо прекратить передавать в открытом виде.

**Comment by Orhideous** [comment]
https://stories.everypony.ru/ уже давно как.
Ну ок, https-only, теперь можно. LetsEncrypt и всё такое, тут даже не надо каких-то особых инструкций.
Джанга сама по себе protocol-agnostic. Close?

**Comment by Orhideous** [comment]
Я к тому, что настройка https для этой CMS ничем не отличается от настройки https на любом другом нормально написаном фреймворке, где протокол не прибит гвоздями.

**Comment by tanriol** [comment]
Это надо бы иметь в составе инструкции по развёртыванию production, если мы её напишем. Лично меня открыть это issue побудило открытие того факта, что stories, развёрнутый сейчас, полностью поддерживает оба протокола... в частности, если ты зашёл по HTTP, то форма логина *не* перенаправляет на HTTPS, чего я как-то ожидал.

**Comment by Orhideous** [comment]
А. Это. Ну тогда это не в issue, а пинать меня.
Смотри, в чем дело.
Я бы с большой радостью отключил http, оставив только https, вот только может отвалиться часть mixed-content, а политик HSTS на каждый чих не понапишешь.
На Табуне я сделал ~~концлагерь~~ cdn.everypony.ru, на котором преимущественно всё и висит. Тут такого нет, а в рассказы вставляют картинки.
Нет, можно, конечно, написать HSTS и разрешить картинки вообще отовсюду. И даже на первых порах так и сделаю.

**Comment by Orhideous** [comment]
HTTPS везде.
