### ISSUE TITLE
Система смены темы сайта

### ISSUE THREAD

**Issue by EpicMan2** [RuFimFiction/ponyFiction#65]
Собственно, необходимо создать систему смены темы нашей любимой библиотеки. Желательно, через настройки пользователя. А тем, кто ещё не определился со своей темой, мы ставим дефолтную тему, которую можно тоже поменять.

**Comment by tanriol** [comment]
Где "тема" - это только CSS или что-то ещё?

**Comment by EpicMan2** [comment]
Да, CSS. Возможно, придётся подхватывать ещё и JS.

**Comment by Orhideous** [comment]
Вынести в настройки пользователя. Тогда надо будет собирать два бандла разных ассетов, и просто грузить нужный.

**Comment by Orhideous** [comment]
Вынести в настройки пользователя. Тогда надо будет собирать два бандла разных ассетов, и просто грузить нужный.

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#64
