### ISSUE TITLE
Заменить memcache на redis

### ISSUE THREAD

**Issue by Orhideous** [RuFimFiction/ponyFiction#67]
Это уберет одно звено с инфраструктуры.

**Comment by andreymal** [comment]
После добавления туевой хучи других звеньев сомнительной нужности звучит примерно как «Доллар резко рухнул на две копейки» в нашей пропаганде.

**Comment by andreymal** [comment]
После добавления туевой хучи других звеньев сомнительной нужности звучит примерно как «Доллар резко рухнул на две копейки» в нашей пропаганде.
