### ISSUE TITLE
It's time to PostgreSQL?

### ISSUE THREAD

**Issue by Orhideous** [RuFimFiction/ponyFiction#68]
После всех мытарств с MySQL и ее форками я хочу поднять вопрос о переезде на PostgreSQL.

Что это даст?
- более простую работу с разворачиванием БД в контейнерах
- нативную поддержку JSON (она нам в будущем **очень** понадобится, в целом, надо уже)
- более легкое администрирование
- широкие возможности для оптимизации запросов, взять те же CTE.

cast @tanriol @HerbSmoker

**Comment by tanriol** [comment]
Принципиальных возражений нет.

**Comment by andreymal** [comment]
И это после переноса миграций на MySQL? Ты странный.

**Comment by Orhideous** [comment]
@andreymal, вот это уж точно никакого отношения не имеет.

**Comment by andreymal** [comment]
Миграции намертво приколотили ponyFiction к MySQL же. Вам их теперь удалять и опять (какой уже по счёту раз?) ломать возможность безболезненного обновления.

**Comment by Orhideous** [comment]
Пока нет релиза, ломать можно что угодно (теоретически). А практически по потребностям.

**Comment by andreymal** [comment]
Я так понимаю, ты сам мазохист и в разработчики набрал мазохистов. Ну ладно.

**Comment by Orhideous** [comment]
@andreymal, переход на личности неуместен. См. шапку выше.
Я описал плюсы, и потребности. Из затрат на работу — миграция основной БД и скрипта.
И _лучше_ написать конструктивное обсуждение вопроса.

**Comment by andreymal** [comment]
Конструктивно — не надо было убирать миграции Django.

**Comment by Orhideous** [comment]
@andreymal Ещё раз, обсуждаются плюсы и минусы перехода на PostgreSQL: что это даст и что для этого надо сделать.

**Comment by andreymal** [comment]
Если бы не убирал миграции Django, то всё, что надо было бы сделать — json-дамп, смена пары строчек в конфиге, загрузка из дампа. На stories.andreymal.org это успешно проделано больше месяца назад, нервы в порядке, багов нет, брат жив.)

**Comment by Orhideous** [comment]
@andreymal Я считаю (обоснованно), что ты переоцениваешь переписывание 1 (одного) файла на другой синтаксис без изменения логики. И что это — не то, о чем надо беспокоиться.
Думать надо о том, что получится в результате.

**Comment by andreymal** [comment]
Я считаю, что ты уже несколько месяцев искусственно создаёшь проблемы, которых не было даже при Веоне (впрочем, не только в сторизе). Можно было ограничиться переписыванием 0 файлов и выкатить постгрес на тестирование хоть прямо сейчас, не сделав ни единого коммита (перенастроить - дело двух минут), но почему-то ты вечно выбираешь сложные пути, а потом начинаешь жаловаться на нетривиальные проблемы (созданные тобой же).

**Comment by tanriol** [comment]
Для чего, кстати, мы хотим поддержку JSON?

**Comment by andreymal** [comment]
Зачем её хотеть? Она в джанге из коробки.

**Comment by Orhideous** [comment]
@tanriol Все слабоструктурированные данные, вида настроек пользователя, можно хранить в json-полях нативно, и делать по ним запросы.

**Comment by Orhideous** [comment]
Да, и один из аргументов, почему я «за» такую миграцию. Постгрес гораздо проще администрировать, в т.ч. в контейнерах.
Сравните тот ужас, который есть у нас сейчас в конфигах `vagga.yaml` + `mysql.conf` (который не всегда корректно работает) с [вот этим](http://vagga.readthedocs.io/en/latest/examples/db/postgres.html)

**Comment by andreymal** [comment]
Несмотря на то, что я не против постгреса — выглядит как искуственно созданные проблемы из-за контейнеров. Почему у меня всегда всё нормально?

**Comment by Orhideous** [comment]
Это не проблемы, а следствия. Объясняю в первый, и, наверное, последний раз.

- чтобы не решать в будущем проблемы по версиям софта
- чтобы держать одинаковые окружения на dev/trunk/prod окружениях
- чтобы иметь полное версионирование всего, и автоматическую выкатку без «инструкции по обновлению»

…надо изолировать софт. При этом необходимо проделать чуть больше работы, чем обычно.

Но это не основное. Суть в том, что такого понятия, как «настройки по умолчанию хост-системы» больше нет, а значит, для определенных программ объемы этой работы разнятся. Пример с mysql и postgres выше.

**Comment by andreymal** [comment]
- проблемы по версиям софта для активно поддерживаемых приложений не существует — они всегда последние, и эти версии всегда совместимы с предпоследними версиями. И не ты ли просил меня выпиливать версии из requirements.txt? ;) Как только разработка станет заброшена — тогда можно заморозить, да. А для активной разработки заморозка только вредна — неработоспособность проекта на новых версиях будет замечена разработчиками сильно поздно, а версия джанги опять устареет, как старый ponyFiction с Django 1.5.

- Держать одинаковые окружения наоборот тоже вредно. Чем более они разнообразны, тем большее число проблем будет замечено и исправлено и тем меньше вероятность глюков при обновлении prod-окружения. Ну и, разумеется, staging для тестирования никто не отменял.

- Автоматическую выкатку делает fabfile — vagga и lithos для этого не требуется. (А сконвертировать vagga.yaml в fabfile.py, думаю, не проблема.) Плюс у вас здесь всего один сервер — хватит даже грамотно написанного shell-скрипта!

Изоляция софта (опять же, активно поддерживаемого) не нужна ни для чего кроме паранойи (зависимости не причина — они всегда последние у всех поддерживаемых проектов). virtualenv также не нужен по той же причине, кстати — `pip install --user` наше всё.

«Настройка по умолчанию хост системы» преобразовалась в «Снос винды/фряхи и установка линукса, пересборка ядра на кастомное для vagga, установка vagga, смена зеркал vagga потому что очередные опять отвалились блджад, освободить место на винде потому что образ убунты не влезает, и только потом наконец выполнить vagga run нормально». Разработчик должен иметь возможность настроить всё что он хочет и как он хочет — для проверки работоспособности на продакшене есть staging. Если, например, он верстальщик — зачем ему пострес, зачем ему редис, зачем ему сфинкс? Зачем ему изоляция в конце концов?

Вывод: всё стало хуже чем было.

**Comment by Orhideous** [comment]
Как придет время, обсудим ещё раз.
