### ISSUE TITLE
Убрать выстрел в ногу

### ISSUE THREAD

**Issue by EpicMan2** [RuFimFiction/ponyFiction#73]
Надо бы сделать так, чтобы модератор\администратор не смог себя забанить.

**Comment by andreymal** [comment]
[А он и не может)](https://github.com/RuFimFiction/ponyFiction/blob/055ba5e76f96f2eea44b1dc8a35aef8c88c3364a/ponyFiction/views/author.py#L132)

**Comment by Orhideous** [comment]
This issue was moved to everypony/ponyFiction#61
